### ISSUE TITLE
Tracking Ecs

### ISSUE THREAD

**Issue by Vlajd** [Tarator-Engine/tarator#12]
- [x] Generic Component Tuple Unwrapping
- [x] Component Iteration
- [x] Entity Iteration
- [x] Component Callbacks
- [ ] Resources

- [ ] Referenced Entity Iterators (in order to avoid using World::entity_collect, which clones)
- [x] Entity Hierarchies
- [ ] custom collection for managing mutated components with unchanged components

Nice to have:
- [ ] Batch entity creation
