### ISSUE TITLE
Tracking GUI progress

### ISSUE THREAD

**Issue by slackers123** [Tarator-Engine/tarator#19]
- [x] add models from fs
- [ ] show components with gui
- [ ] gizmos
- [ ] modifying components and entities with gui
