### ISSUE TITLE
Tracking Renderer Progress

### ISSUE THREAD

**Issue by slackers123** [Tarator-Engine/tarator#6]
This issue will be used to track the progress of the renderer.

- [x] Basic Gltf Importing as of [d44da75](https://github.com/Tarator-Engine/Tarator/commit/d44da757c7fa672fc442cfb51be36bc1c8f6f7ff)
- [x] Refactored Gltf Importing as of [e6afadf](https://github.com/Tarator-Engine/Tarator/commit/e6afadf61390099d402058113b041d99b57714b7)
- [x] Gltf Importing Tests [26da5f4](https://github.com/Tarator-Engine/Tarator/commit/26da5f45d4aa045b6c6b4c245e0fd6786af06c73)
- [x] Basic PBR Renderer
- [x] Decide on whether or not to use a render graph
